#!/usr/bin/env python

Import("env")

lib_path = "#backend/target/release"
lib_name = "neb_utils"
header_path = "#core/util/"

env.Append(LIBPATH=[lib_path])
env.Append(LIBS=[lib_name])
env.Append(CPPPATH=[header_path])
